apiVersion: 1
datasources:
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
- name: Pyroscope
  type: phlare
  access: proxy
  orgId: 1
  url: http://pyroscope:4040
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
- name: Postgres
  type: postgres
  url: postgres:5432
  user: ${POSTGRES_USER}
  secureJsonData:
    password: ${POSTGRES_PASSWORD}
  jsonData:
    database: postgres
    sslmode: 'disable' # disable/require/verify-ca/verify-full
    maxOpenConns: 100 # Grafana v5.4+
    maxIdleConns: 100 # Grafana v5.4+
    maxIdleConnsAuto: true # Grafana v9.5.1+
    connMaxLifetime: 14400 # Grafana v5.4+
    postgresVersion: 1500 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
    timescaledb: false